@{
  Main = @{
    IncludedPathPatterns = @(
      'apps/chart/state/data/raw/BaseLine/**'
    )
    # These are disposable even inside a normally included BaseLine or archive.
    ForbiddenArtifactPatterns = @(
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.vite/**',
      '**/cache/**',
      '**/caches/**',
      '**/.cache/**',
      '**/tmp/**',
      '**/temp/**',
      '**/temporary/**',
      '**/__pycache__/**',
      '**/.pytest_cache/**',
      '**/.mypy_cache/**',
      '**/.ruff_cache/**',
      '**/.benchmarks/**',
      '**/*.egg-info/**',
      '**/.venv/**',
      '**/venv/**',
      '**/env/**',
      '**/coverage/**',
      '**/htmlcov/**',
      '**/.coverage',
      '**/coverage.xml',
      '**/*.pyc',
      '**/*.pyo',
      '**/*.tmp',
      '**/*.temp',
      '**/*.bak',
      '**/*.pid',
      '**/*.swp',
      '**/*.swo',
      '**/*.orig',
      '**/*.rej',
      '**/*.part',
      '**/*.crdownload',
      '**/*~'
    )
    ExcludedPathPatterns = @(
      'engineering/verification/history/cleanup-2026-09-29/pre-cleanup-project.zip',
      'engineering/verification/single-root-2026-09-29/project-before-migration.zip',
      'apps/chart/node_modules/**',
      '**/node_modules/**',
      'apps/chart/dist/**',
      '**/.vite/**',
      'apps/chart/state/cache/**',
      'apps/chart/state/secret/**',
      'apps/chart/state/tmp/**',
      'apps/chart/state/data/raw/**',
      'engineering/archive/repository-graphify/cache/**',
      'graphify-out/cache/**',
      'engineering/archive/repository-graphify/**/cache/**',
      'engineering/archive/repository-graphify/**/last_query_stamp',
      'engineering/archive/repository-graphify/**/raw-run/.graphify_*.json',
      'engineering/archive/repository-graphify/**/raw-run/.graphify_root',
      'engineering/archive/docs/validation-temp/**',
      'engineering/verification/**/runtime-server.*',
      '**/__pycache__/**',
      '**/*.pyc',
      '**/.pytest_cache/**',
      '**/.mypy_cache/**',
      '**/.ruff_cache/**',
      '**/*.egg-info/**',
      '**/.coverage',
      '**/coverage/**',
      '**/htmlcov/**',
      '**/.benchmarks/**',
      '**/.cache/**',
      '**/*.tmp',
      '**/*.temp',
      '**/*.bak',
      '**/*.pid',
      '**/.venv/**',
      '**/venv/**',
      '**/env/**',
      '**/.env',
      '**/.env.*',
      '.env',
      '.env.*',
      '**/.idea/**',
      '**/.vscode/**',
      '**/.DS_Store',
      '**/Thumbs.db',
      '**/Desktop.ini',
      '**/.worktrees/**',
      '**/.superpowers/**'
    )
    MeaningfulRoots = @(
      'apps/chart/tests/',
      'engine/tests/',
      'engineering/',
      'apps/chart/state/data/raw/BaseLine/'
    )
  }
  Sensitive = @{
    PathPatterns = @(
      'apps/chart/state/secret/**',
      '**/apps/chart/state/secret/**',
      '*.pem',
      '**/*.pem',
      '*.key',
      '**/*.key',
      'id_rsa',
      '**/id_rsa',
      '.env',
      '**/.env',
      '.env.*',
      '**/.env.*'
    )
    ContentPatterns = @(
      '-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----',
      '\bgh[pousr]_[A-Za-z0-9_]{20,}\b',
      '\bgithub_pat_[A-Za-z0-9_]{20,}\b',
      '\bAKIA[0-9A-Z]{16}\b'
    )
    MaximumScanBytes = 1048576
  }
  Production = @{
    MandatoryPaths = @(
      'scripts/launch.bat',
      'scripts/start.ps1',
      'apps/chart/package.json',
      'apps/chart/package-lock.json',
      'apps/chart/vite.config.js',
      'apps/chart/index.html',
      'apps/chart/review.html',
      'apps/chart/scripts/dev-server.mjs',
      'engine/__init__.py',
      'engine/bridge/trading_pipeline.py'
    )
    RuntimeRoots = @(
      'apps/chart/',
      'engine/',
      'scripts/'
    )
    ExcludedPathPatterns = @(
      'apps/chart/state/**',
      'apps/chart/tests/**',
      'engine/tests/**',
      'apps/chart/node_modules/**',
      'apps/chart/dist/**',
      'engineering/**',
      'scripts/git/**',
      'scripts/verification/**',
      'docs/**',
      'engine/algorithms/**',
      '**/*.zip',
      'engine/bridge/__init__.py',
      'apps/chart/server/raw-integrity.js',
      '**/__pycache__/**',
      '**/*.pyc'
    )
  }
}
