"""Persist forensic conclusions; this does not load or alter production engines."""
from pathlib import Path
import json

OUT=Path(__file__).resolve().parent
SOURCE={i['path'].replace('\\','/'):i for i in json.loads((OUT/'source-map.json').read_text())}
F=[]

def add(id,title,severity,confidence,direction,category,modules,functions,trigger,expected,actual,first,root,chain,raw,source,reference,impact,mirror,repro,fix,regression):
    versions=[]
    for module in modules:
        meta=SOURCE[module]['metadata']
        versions.append(module+': '+('; '.join(k+'='+str(v) for k,v in meta.items()) or 'unversioned'))
    F.append(dict(zip(('BUG ID','TITLE','SEVERITY','CONFIDENCE','DIRECTION','CATEGORY','AFFECTED MODULE(S)',
        'AFFECTED VERSION(S)','FUNCTION / METHOD','TRIGGER CONDITIONS','EXPECTED BEHAVIOR','ACTUAL BEHAVIOR',
        'FIRST DIFF','ROOT CAUSE','STATE CHAIN','RAW EVIDENCE','SOURCE EVIDENCE','ALGORITHM REFERENCE',
        'DOWNSTREAM IMPACT','MIRROR IMPACT','REPRODUCTION','GENERAL FIX DIRECTION','REGRESSION TEST REQUIRED'),
        (id,title,severity,confidence,direction,category,['engine/'+m for m in modules],versions,functions,trigger,
        expected,actual,first,root,chain,raw,source,reference,impact,mirror,repro,fix,regression))))

add('RX-01','Initial confirmed Reaction omits eligible confirmation-candle continuation','HIGH','CONFIRMED','Both',
    'Calculation implementation',['pipeline/reaction_engine.py'],
    'UnifiedReactionDetector.detect; _candidate_from_confirmation_remainder',
    'The initial confirmed Reaction has a Break main candle with the required next First color, a qualifying confirmation remainder, no post-confirmation Reset, and a later strict confirmation.',
    'Apply the normal confirmation remainder transition to the initial confirmation and admit its eligible next Mode B candidate.',
    'Initial detection starts at BreakIndex+1 with candidate=None, so the eligible Break-candle First is absent from canonical Reactions.',
    'Immediately after initial confirmation, next candidate should own First=BreakIndex; actual candidate is None, before Blue or lifecycle execution.',
    'The initial-state branch omits the shared remainder-seeding call that all later confirmation branches perform.',
    'RAW -> initial Reaction strict confirmation -> remainder First -> missing canonical identity -> downstream canonical consumers.',
    'Original idx6 XAUUSD 14,140 five-second rows at main30s. Bullish First 2026-09-16 22:42:00, Break22:44:00, confirmation22:44:05 +03:30. Eligible continuation (First18,Break19) confirms in main22:44:30; box4249.81/4244.635. Canonical identity(18,19) is missing. Bearish market occurrence not independently established.',
    'reaction_engine.py:2148-2157 and2183-2195; contrasting shared calls2308,2349,2387 and contract1589.',
    'Both V5.4.24 §4.4 L80 permit confirmation-candle reuse; Source shared-state contract says every confirmation opens Normal search. Newline-normalized embedded Source preserves the same omission. Current Source has precedence, but its inconsistent transition plus reproduced eligible continuation support implementation-defect classification.',
    'Canonical membership and numbering are incorrect. Missing Reaction can alter Blue/A/Order discovery. Exact accepted trade, S/E/StopAll consequences were not counterfactually executed.',
    'Both valid synthetic reflections omit(2,3): actual[(1,2)] versus expected[(1,2),(2,3)].',
    'python -B engineering/verification/forensic-audit-2026-10-05/reaction-audit/probes.py; then python -B engineering/verification/forensic-audit-2026-10-05/reaction-audit/raw_probes.py. See reaction-audit/probe-evidence.json and reaction-audit/raw-evidence.json.',
    'Correct the initial Reaction state transition in its owning detector using the same general confirmation remainder contract, preserving exact Reset precedence.',
    'Both directions, confirmation reused with/without Reset, equality boundary, initial versus later confirmation parity, then full-engine first-divergence regression on real input.')

add('BL-01','Two Scale strike paths consume Break-candle extrema after exact confirmation','HIGH','CONFIRMED','Both',
    'Calculation chronology',['pipeline/blue_line_detector.py'],
    'count_scale_strikes; _intrabar_pending_confirmation',
    'A Break main candle reaches its eligible directional extreme after its first exact Reaction confirmation; either the main candle has confirming color or no eligible strike existed at first confirmation.',
    'Limit Break strike evidence through the first exact confirmation lower row, inclusive, independently of pending strike eligibility.',
    'Full-main pending extrema can confirm directly; the lower loop also continues after first strict confirmation when eligible is empty.',
    'Pending/strike state first includes an extreme attained after the owning Reaction confirmation. The divergence precedes scale spacing and public filtering.',
    'The full-main confirming-color shortcut bypasses the lower cutoff; the lower helper uses breaks AND eligible instead of an unconditional owning-Reaction confirmation boundary.',
    'RAW exact confirmation -> later Break extreme -> wrong strike/source state -> Blue calculation provenance -> A Blue-2 provenance.',
    'Five real idx6/idx9 cases are recorded in reaction-audit/REPORT.md. Example Bullish Reaction58: main2026-09-17 05:30:30 confirms05:30:35, eligible Low4299.06, actual strike4298.815 first attained05:30:45 +03:30. Example Bearish Reaction42: 2026-09-29 07:00:00 confirms07:00:00, eligible High4139.515, later actual4140.305 at07:00:20. None immediately emits a Scale Blue due separate spacing suppression.',
    'blue_line_detector.py:162-188 and103-135; strict termination conditional at118.',
    'Both V5.4.24 §5.2 L106 and reconstruction row617 cap Break intrabar confirmation. Higher-authority Source is internally inconsistent with exact Reaction chronology; independently reproduced in both branches.',
    'Bounded eligibility oracle changes Bearish Blue ordinal146 source from2026-09-30 03:23:00/index2984/line4184.93 to03:22:30/index2983/line4184.305. A ordinal50 inherits changed Blue-2 source; its price4187.69/source03:26:30 stay equal. The Blue is internal, but its A consumer demonstrates calculation propagation. Final public A/S/E/trade counterfactual NOT RUN.',
    'Both branches reproduce both directions. Pre-confirmation Low9.1 stays aboveFib8.764; laterLow5 at12:01:15 leaks afterconfirmation12:01:00. Reflected High-5 leaks likewise.',
    'python -B engineering/verification/forensic-audit-2026-10-05/reaction-audit/probes.py; then python -B engineering/verification/forensic-audit-2026-10-05/reaction-audit/raw_probes.py. The oracle runs in a separate namespace and never changes production globals or RAW.',
    'Enforce exact Break cutoff in the Blue strike owner for every entry path; preserve earlier eligible extreme ownership and strict first-equal source semantics.',
    'Confirming-color and pending-intrabar paths, empty eligible at first break, same-row inclusivity, later equal extreme, both mirrors, full pipeline provenance comparisons.')

add('SE-01','E route reduction discards the required later First on equal Order stop','HIGH','CONFIRMED','Both',
    'Calculation selection',['pipeline/e_zone_detector.py','pipeline/order_audit_engine.py'],
    'EZoneDetector._zone; OrderAuditEngineMixin.order_candidates; _first_order; _post_stop_accepted_orders_for_parent',
    'Multiple eligible canonical physical Orders in the same E parent branch have the identical first strict Order-stop event and different First indices.',
    'For E consumption choose earliest exact stop, then larger FirstIndex for a true stop tie, across all eligible routes.',
    'Route-specific selection retains an earlier First before the final correct tie key executes.',
    'The native order_candidates pool contains both identities, but _first_order/other one-member route reductions discard the later First. E final (stop,-First) cannot recover it.',
    'Creation ordering by confirmation/ascending First is reused during consumption; inconsistent minima are computed before global E adjudication.',
    'Canonical direct-parent and accepted reset-leg Orders -> same exact stop -> early route minimum -> E construction with wrong Order -> final-visible E geometry/provenance.',
    'idx8 complete XAUUSD 68,492 five-second rows main30s: four unique final-visible rows, two per direction. Bull RedE5 source2026-09-29 21:28:00, parentstop21:10:05, selected(2825,2839) confirms21:24:15 versus eligible(2841,2847) confirms21:28:25; exact stop21:30:00 both. Actual A/250 box4146.525/4143.415 stop4147.6 versus required B/251 box4143.7/4142.71 stop4146.525. Other cases: BullBlueE1 2026-09-30 12:37:30; BearBlueE1 2026-09-29 21:03:30; BearRedE4 2026-10-02 08:02:00, all +03:30.',
    'E:391-418 retains route[0]; Order:830-856 uses ascending FirstTime and first result; post-stop route1366-1374 ranks confirmation ahead of later First.',
    'Both V5.4.24 §8.2 L185-187 and E matrixrow620 require larger FirstIndex after equal stop. §9.1 earliest confirmation is the separate physical creation rule, not E consumption. Source precedence is recorded; native same-pool eligibility and inconsistent final key establish an implementation error.',
    'Four final E rows select wrong Order identity/mode/number/box/stop. Twenty unique physical branch conflicts were traced;334 route observations/324 survivors/52 provisional variants are NOT final defect counts. Subsequent accepted orders after correcting E were not simulated.',
    'Both mirrored synthetic probes and two real final E cases in each direction.',
    'python -B engineering/verification/forensic-audit-2026-10-05/trace_pipeline.py --raw-index 8 --timeframe 30 --order-ties; then python -B engineering/verification/forensic-audit-2026-10-05/s-e-audit/raw_tie_analysis.py. s-e-audit/RAW-tie-confirmation.json verifies native pool eligibility, exact stop tie and final-output joins. Traced stable payload equals uninstrumented payload.',
    'Own the E consumption comparator over the complete eligible physical set; ensure each route uses that same minimum before reducing. Preserve independent creation/one-parent-stop rules.',
    'Direct parent versus reset leg, inherited/carried/post-stop routes, equal stop with unequal confirmations, two directions, exact final E identity and geometry, repeated stable rebuild.')

add('RX-02','Sparse first buckets inflate Reaction timeframe and misassign Reset ownership','HIGH','CONFIRMED','Both',
    'Calculation chronology',['pipeline/reaction_engine.py','bridge/trading_pipeline.py'],
    'DetectorBase.__init__; post_breakout_reset; UnifiedReactionDetector.detect; build_candle_buckets',
    'Valid supplied main buckets omit an empty bucket between the first two occupied starts, so their gap exceeds the requested main timeframe.',
    'Use the explicit requested timeframe for each half-open main/lower window and map the exact Reset to its containing main bucket.',
    'DetectorBase infers the larger first occupied gap as timeframe; confirmation remainder scans into a later main candle and assigns its Reset to the previous index.',
    'Detector initialization has timeframe60 while request/MarketChronology have30; first observable Reset then uses index2 instead of3.',
    'Timeframe metadata is inferred from occupancy rather than passed consistently through the calculation context.',
    'Accepted sparse transport -> 30s bucket list with a60s first gap -> inferred60 detector -> overlong lower window -> wrong Reset main identity.',
    'Synthetic consistent occupied30s starts2026-10-05 12:00:00,12:01:00,12:01:30,12:02:00; six5s rows per occupied candle. Exact Reset12:02:00 is attached to main12:01:30/index2 instead of12:02:00/index3. These dates identify the probe only, not production rules. No original RAW prefix case was established.',
    'Reaction:121-124; post_breakout_reset278-283 and Unified2174-2193. Bridge164-177 preserves sparse occupancy and MarketChronology1749-1750 receives explicit timeframe.',
    'Both V5.4.24 global chronology L56/§4.6 L88 require correct owning main and exact event order. Selected-range contract L47 and audited chart transport explicitly preserve missing buckets; the fixture is an accepted input shape.',
    'Reset identity/time and subsequent search boundaries can be wrong across the stream. Full accepted trade counterfactual NOT RUN; real supplied RAW-prefix incidence unproven.',
    'Both directions reproduce the same owner misassignment; range boundary independently validated by500 sparse histories/2500 assertions.',
    'python -B engineering/verification/forensic-audit-2026-10-05/reaction-audit/probes.py; see boundary-audit/REPORT.md and its executable probe for transport acceptance.',
    'Own timeframe in the run context and pass it to Reaction/lower-window consumers; never infer duration from occupied timestamps.',
    'Sparse prefix/middle gaps, cold selected range, complete-source range, one-candle input,30/60s, exact bucket boundary, mirrors; assert event belongs to declared half-open bucket.')

add('BR-01','Accepted optional StopAll-engine omission causes feedback/final mismatch crash','HIGH','CONFIRMED','Direction-invariant',
    'CLI orchestration',['bridge/trading_pipeline.py'],
    'parse_arguments; load_engines; calculate_direction_with_order_b_feedback; finalize_direction_visibility',
    'Valid RAW with E/Order_B activity is calculated while optional --lifecycle-engine/--stopall-engine is omitted.',
    'One effective enablement decision must be used in feedback and final visibility; every parser-accepted supported configuration should complete consistently.',
    'Fallback loads lifecycle and feedback uses StopAll, but final visibility gates it on the absent explicit argument, then crashes comparing accepted reset-leg identities.',
    'StopAll participation diverges between feedback input at2203 and final gate2511 before identity comparison2559.',
    'Effective module loading/default state is not the configuration authority for every orchestration stage.',
    'CLI omission -> fallback lifecycle -> feedback StopAll -> accepted Order_B identities -> empty final StopAll -> different identities -> RuntimeError.',
    'idx6 XAUUSD 14,140 valid5s rows main30s, both directions. Explicit-path control exits0; omitted-path exits1 with error Final Order_B lifecycle causes differ from converged E feedback.',
    'Bridge1635-1640 optional parser;1694-1699 fallback;2203-2219 unconditional feedback;2511-2519 conditional final;2559-2562 invariant failure.',
    'V5.4.24 §13.3 enablement fields do not decide default-on versus default-off. Either interpretation requires consistent stage inputs; the crash is confirmed without inventing a trading default.',
    'The accepted CLI configuration produces no successful calculation payload. Normal explicit-path production matrix succeeds.',
    'Direction-invariant orchestration defect; command --direction both reproduces.',
    'python -B engineering/verification/forensic-audit-2026-10-05/check_configurations.py; exact CLI/path/RAW/flags preserved in configurations/manifest.json; error file without-stopall-engine.stdout.json.',
    'Resolve effective lifecycle enablement once in the bridge and reuse it throughout feedback/finalization; select and document the optional default before repair.',
    'Explicit/omitted module paths, E on/off, both and separate directions, histories with/without StopAll and reset legs; assert converged and final identities match.')

add('OA-INDEX-01','Restored accepted Order ledger rows lack the confirmation secondary index','MEDIUM','CONFIRMED','Both',
    'State/index integrity',['pipeline/order_audit_engine.py'],
    'ensure_accepted_order_audit; _rebuild_accepted_order_audit; _accepted_post_stop_orders_after',
    'An accepted historical/reset-leg physical Order is preserved, absent from the rebuilt subset, and merged back after a ledger rebuild.',
    'Every retained eligible ledger identity must be discoverable through the same confirmation index used by accepted post-stop queries.',
    'setdefault restores the row but not its confirmation index; query returns[] although identity(5,6) exists in the ledger.',
    'At the restoration merge, ledger membership becomes populated while the rebuilt confirmation index remains missing the identity.',
    'A mutation of canonical state updates only one of its coupled structures; cache invalidation alone does not populate the secondary index.',
    'Accepted ledger -> rebuild clears/reindexes subset -> preserved identity merged -> index omission -> accepted post-stop E query misses it.',
    'Source-level both-direction fixture is the existing strict xfail; actual market loss was not established. Current direct order_b_legs scanning may mask this in common full-pipeline paths.',
    'Order1590-1611 preserves and setdefaults; query1340-1374 relies on confirmation index; compare normal _index_order_audit_identity path. Existing test_order_audit_lifecycle_contracts.py:266-286.',
    'Reference §11/§13 identity and accepted physical ledger requirements; decisive evidence is existing explicit desired-query regression plus canonical/index inconsistency. No novel market rule is required.',
    'Accepted physical evidence is unavailable to this query. A general final-output corruption claim is unproven; two expected failures already describe this defect.',
    'Existing paired strict expected failures reproduce both directions.',
    'python -B -m pytest -q engine/tests/unit/test_order_audit_lifecycle_contracts.py -k ensure_restored --runxfail -p no:cacheprovider ->2 failed,37 deselected; restored-index-failures.log.',
    'Restore ledger and all semantic indexes atomically through the canonical registration owner; preserve history and invalidate dependent caches together.',
    'Rebuild then restore, repeated ensure, ledger/query equivalence, no duplicates, both directions, restored active/inactive legs, full-engine route reachability.')

add('SE-02','Shared Order reconciliation leaves converted Red S with null Order direction','MEDIUM','CONFIRMED','Both',
    'Conditional provenance/schema',['pipeline/s_zone_detector.py','bridge/trading_pipeline.py'],
    'SZoneDetector.reconcile_shared_order_stops; serialize_s_zones',
    'An initially order-free Type3/Type4 S acquires an authoritative physical opposite Order during shared stop reconciliation.',
    'Populate the physical Order direction together with its identity, geometry and chronology, as native Order-backed S construction does.',
    'Conversion sets Red and physical Order fields but leaves order_direction=None; serializer emits null.',
    'Immediately at replace in reconciliation, new Order identity is populated while its direction remains the order-free value.',
    'Duplicated Order-backed constructor/replacement logic omits a field in the reconciliation owner.',
    'Order-free S -> accepted physical shared Order stop -> Red replacement with stale null provenance -> JSON null.',
    'Both valid synthetic chronology probes: S source00:01:00, Astop00:00:35, physical confirmation00:01:10, decision/stop00:01:30. This stays after A gate and is independent of SE-03. No public occurrence found in21 saved calculations scanned.',
    'S562,1030 initializeNone;1393-1417 replace omitsdirection; ordinary construction1193 sets opposite; Bridge345,349 serialize retained field.',
    'Both V5.4.24 §7.6 L175-177 keeps physical Order authority; mirror opposite-Order row near558 and schema§13.2 L316 include orderDirection. Native constructor supplies unambiguous control.',
    'Incorrect S provenance/schema under the conditional route. Current RAW prevalence and accepted trading effect unproven.',
    'Expected bearish physical direction in Bullish behavior and bullish in Bearish behavior; both getNone.',
    'python -B engineering/verification/forensic-audit-2026-10-05/s-e-audit/probes.py; case shared_s_direction_after_a_gate in probe-results.json.',
    'Make shared physical Order adoption populate the same complete provenance contract as native Order-backed S, in S ownership rather than serializer.',
    'Both order-free builders, both directions, valid post-A-gate decision, repeated reconcile, immutable physical creator, legacy/Bridge field equality.')

add('NUM-JSON-01','Numeric JSON loses exact OHLC distinctions before Decimal normalization','MEDIUM','CONFIRMED','Direction-invariant',
    'Input numeric precision',['bridge/trading_pipeline.py','pipeline/core_utils.py'],
    'prepare_market_context RAW loading; build_candle_buckets.cached_decimal; as_decimal',
    'Accepted numeric JSON OHLC lexemes differ by less than their binary floating point resolution.',
    'Preserve supplied exact price distinctions before any color, strict crossing or Decimal-sensitive decision.',
    'orjson.loads materializes floats; unequal prices round to100.0 before as_decimal(str(value)). A valid RED candle becomes GREEN equality/Doji.',
    'RAW decoding converts exact distinct lexemes into equal floats, before bucket aggregation or detector construction.',
    'Decimal conversion occurs after a lossy numeric parser; type/value Decimal caching cannot recover discarded digits.',
    'Valid numeric JSON -> binaryfloat100.0 values -> Decimal100.0 -> wrong candle tag and potential strict equality decisions.',
    'Synthetic internally consistent numeric row: Open100.0000000000000002, High100.0000000000000003, Low100.0000000000000000, Close100.0000000000000001. ExpectedRED, actualGREEN. String-price control retains exactRED. No current market RAW precision loss demonstrated.',
    'Bridge RAW orjson.loads near1720; Decimal cache131-145; core_utils.as_decimal normalizesstr. Exact parser and loaded result in numeric-input-results.json.',
    'Both V5.4.24 global exact Decimal requirement L53/57 and GREEN Doji rule L54. Doji rule is correctly implemented on already-normalized values; input normalization is owning divergence.',
    'Wrong input candle color/equality under narrow high-precision numeric input; downstream price-sensitive decisions may differ. No current supplied-market corruption claim.',
    'Direction-invariant price decoding; Doji remains GREEN in both market directions.',
    'python -B engineering/verification/forensic-audit-2026-10-05/check_numeric_input.py; results preserve inputlexemes, expected/actual and string control.',
    'Define and enforce exact price representation at RAW ingestion before numeric decoding; preserve lexemes or validate/document a string-price contract. Correct owner is ingress, not later comparisons.',
    'Numeric/string equivalence at supported precision; distinct/equal lexemes; large/small magnitudes; exponent form; exact color and strict crossing boundary; immutable RAW.')

add('LC-01','S-transition visibility helper maps intrabar event to the next main candle','LOW','CONFIRMED','Direction-invariant',
    'Scoped documented-helper defect; trading impact unproven',['pipeline/lifecycle_engine.py','bridge/trading_pipeline.py'],
    'visible_a_zones_after_s_stops; final visibility caller',
    'A confirmed S transition/decision event falls strictly inside a main candle rather than at its start.',
    'Under this helper documented contract, suppress the A candle containing the confirmed transition event.',
    'bisect_left returns the next main start, so the helper removes an A in the following candle.',
    'Computed excluded index is2 at event00:00:35, whereas containing candle00:00:30 isindex1.',
    'Insertion-point index is used where a containing-bucket floor index is required.',
    'Exact S decision -> left insertion main index -> wrong A visibility candidate exclusion.',
    'Four unique idx8 real pairs are in lifecycle-audit/REPORT.md, e.g. Bullish decision2026-09-30 03:52:25 maps toA03:52:30 instead ofcontaining03:52:00 +03:30. All four A are independently calculation-invalid, so observed final impact is masked.',
    'Lifecycle549-556; MarketChronology.main_index usesbisect_right-1; relevant finalcallerBridge2502-2506. Earlier candidate_a1977 is unused.',
    'Direct Source doc544-547 says containing confirmed transition. Reference§12.6 has a generic exact-stop rule but does not settle the helper S-decision versus own-stop terminology. This is a confirmed local documented-helper mismatch, not a confirmed normative trading visibility bug.',
    'Conditional helper output excludes the wrong candle. No demonstrated final public difference on real RAW; changing the trading visibility event contract requires clarification first.',
    'Both helper directions reproduce identical temporal mapping.',
    'python -B engineering/verification/forensic-audit-2026-10-05/lifecycle-audit/probes.py; saved trace join proves real reachability and independent invalidA masking.',
    'Resolve the intended transition event semantics, then use the shared containing-candle index contract in lifecycle visibility.',
    'Inside/start/end main boundary, no next candle, gaps, both directions; require an otherwise valid A to prove final visibility impact.')

add('API-LEGACY-01','Legacy pipeline package wrapper imports a missing symbol','LOW','CONFIRMED','Direction-invariant',
    'Unsupported legacy API defect; not production trading',['pipeline/__init__.py','pipeline/blue_line_detector.py'],
    'pipeline package import',
    'A caller imports the packaged pipeline wrapper with the same flat dependency path available as the current Bridge loader.',
    'An offered package wrapper resolves its declared imports, or is deliberately retired with a consistent public boundary.',
    'Import raises ImportError because run_blue_line is absent from blue_line_detector.',
    'Import resolution at pipeline/__init__.py fails before calculation.',
    'Legacy wrapper references a removed/renamed symbol and was not synchronized.',
    'Python package import -> missing exported symbol -> import failure.',
    'No RAW is needed. Current production Bridge flat imports succeed and full RAW execution is unaffected.',
    'pipeline/__init__.py import statement; complete blue_line_detector.py has no run_blue_line definition. package-import.log.',
    'V5.4.24 §13.9/§14.3 explicitly documents the pre-existing unsupported wrapper. Therefore maintainability/API debt, not a newly discovered algorithm regression.',
    'Only consumers of that legacy wrapper fail; current production trading path does not use it.',
    'Direction-invariant import failure.',
    'python -B engineering/verification/forensic-audit-2026-10-05/check_legacy_import.py reproduces the isolated packaged pipeline import failure; package-import.log preserves the traceback. No detector patch.',
    'Deliberately retire the wrapper or align its exports with the supported API after confirming intended public surface.',
    'Supported import smoke test; preserve current flat loader and exact module identity.')

add('LC-03','Unstopped invalid live heads do not block Orders until a future stop appears','MEDIUM','HIGH-CONFIDENCE','Both',
    'Documented lifecycle invariant; full market impact unproven',['pipeline/lifecycle_engine.py'],
    'blocked_orders_while_invalid_leg_heads_are_live; resolve_order_context',
    'An invalid A leg head remains live at input end; an opposite First occurs after its source but before any future strict head stop.',
    'Under the helper live-until-stop contract, block the open live interval as well as closed intervals.',
    'No stop returned causes the head to be skipped. Appending a later first stop retroactively changes the already-existing blocked First set.',
    'Prefix blockset[] becomes[oppositeFirst] after future lower row is appended, although the First event already occurred inside the same live interval.',
    'None stop is interpreted as no blocking interval rather than an open-ended interval.',
    'Invalid live A -> no stop in prefix -> Order First permitted -> future strict stop -> historical First veto changes.',
    'Both synthetic production chronology probes: headsource00:00:30, First00:01:00, prefixthrough00:01:30 no stop; appended00:01:35 strict stop blocks First. Actual SZoneDetector.first_a_stop/MarketChronology used; full-market accepted Order consequence not established.',
    'Lifecycle825-835; helper contract821-823; resolve_order_context518 and Bridge2044-2056.',
    'Source doc says blocked while invalid head remains live until stop. References§11/12.6 give general validity ownership but not the exact open interval. A post-stop prerequisite interpretation remains possible only by changing the documented contract.',
    'Returned blockset is prefix-sensitive. Potential accepted Order/lifecycle lookahead remains HIGH-CONFIDENCE until native accepted-output and normative interval are established.',
    'Both real detector/chronology reflections reproduce the same prefix change.',
    'python -B engineering/verification/forensic-audit-2026-10-05/lifecycle-audit/probes.py; corresponding paired invalid-head no-stop cases in probe-results.json.',
    'Clarify live interval authority; handle an unresolved end in the lifecycle interval owner if open intervals are normative, preserving accepted independent causes.',
    'Prefix extension before/at/after stop; equality; accepted independent A causes; both directions; actual Order creation joins.')

add('LC-04','Final A visibility can use older priority stop instead of newest stopped boundary','MEDIUM','HIGH-CONFIDENCE','Both',
    'Lifecycle/visibility rule discrepancy',['pipeline/lifecycle_engine.py'],
    'visible_a_zones_after_module_boundaries; dominant_module; split_a_zones_by_dominant_stops',
    'An older high-priority owner stopped before a newer lower-priority owner was created; A provenance starts after the old stop but before the newest stop.',
    'Use newest stopped-owner main boundary first, then priority for the appropriate tie, as calculation validation and§12.6 describe.',
    'Final visibility selects the older Red owner by priority and publishes the A that spans the newer Blue stop boundary.',
    'Final provenance boundary selection chooses historical Red stop00:00:45 instead of newest Blue stop00:01:35.',
    'A duplicated owner comparator omits chronological stop recency from final visibility while calculation validation includes it.',
    'Old Red stopped -> independent newer Blue stopped -> A provenance crossing latest stop -> wrong final boundary owner.',
    'Both synthetic helper probes: Redsource00:00:00 stop00:00:45; Bluesource00:01:00 stop00:01:35; Asource00:02:00 provenance00:01:00. Independent E roots can structurally coexist, but no real final-output counterexample was established.',
    'Lifecycle1266-1284/601-610 versus calculation714-725.',
    'Both V5.4.24§12.6 L303 newest stopped owner. Earlier high priority surviving beyond newer decision is a legitimate alternative case; probe explicitly stops old owner before new source to refute it.',
    'Potential final A provenance visibility disagreement; actual full-pipeline market effect unproven.',
    'Both paired visibility helper outputs reproduce priority choice.',
    'python -B engineering/verification/forensic-audit-2026-10-05/lifecycle-audit/probes.py; see LC-04 in REPORT.md.',
    'Define one authoritative lifecycle boundary comparator shared by calculation and final provenance visibility; retain surviving larger-owner exceptions explicitly.',
    'Older stopped versus older still-live high priority, newest-stop ties, independent roots, both directions, final accepted A provenance joins.')

add('RX-H01','Bounded geometry helper prioritizes First index over exact confirmation time','MEDIUM','HIGH-CONFIDENCE','Both',
    'Method contract; accepted Order impact unproven',['pipeline/reaction_engine.py'],
    '_earliest_confirmed_geometry; Order candidate caller closure',
    'Nested geometry candidates confirm in the same main candle at different exact lower timestamps; earlier First confirms later.',
    'Under the method first-strict-confirmation contract, compare exact lower confirmation time before First/Break tie ordering.',
    'Within the same main candle, min(confirmed,key=first_idx) chooses an earlier First whose confirmation is ten seconds later.',
    'Geometry helper selects First1 confirming12:02:10 overFirst3 confirming12:02:00.',
    'Main-candle completion grouping loses exact confirmation ordering before First-index reduction.',
    'Bounded geometry candidates -> same Break main -> wrong local minimum -> possible physical-Order candidate, then canonical membership guard.',
    'Both synthetic nested-candidate probes. No accepted physical Order RAW counterexample; later First may be noncanonical while the initial owner remains healthy.',
    'Reaction1917-1924 contract;1987-1988 reduction; separate canonical membership/Order creation checks remain authoritative.',
    'Source method contract and both V5.4.24§9.1 L211 earliest canonical confirmation thenFirst/Break. Geometry candidates are not interchangeable with canonical accepted registry.',
    'A local contract discrepancy is reproduced, but accepted Order chronology defect is not confirmed because downstream membership can refute it.',
    'Both geometry reflections select the same wrong local index.',
    'python -B engineering/verification/forensic-audit-2026-10-05/reaction-audit/probes.py; earliest geometry case.',
    'Resolve helper contract versus canonical candidate requirements before changing order; keep creation and consumption comparator contracts distinct.',
    'Same-main differing exact confirmation, canonical/noncanonical candidates, tie events, both directions, accepted Order causal join.')

assert len(F)==13
assert all(len(i)==23 for i in F)
(OUT/'findings.json').write_text(json.dumps(F,indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps({'findings':len(F),'confirmed':sum(i['CONFIDENCE']=='CONFIRMED' for i in F),
                  'highConfidence':sum(i['CONFIDENCE']=='HIGH-CONFIDENCE' for i in F)},indent=2))
