const field = (id, type, en, fa, tags = []) => ({ id, type, names: { en, fa }, tags });

const commonEvent = [
  field("direction", "enum", "Direction", "جهت", ["direction"]),
  field("sourceIndex", "integer", "Source candle index", "شماره کندل منبع", ["source"]),
  field("sourceTime", "datetime", "Source time", "زمان منبع", ["source", "time"]),
  field("price", "decimal", "Price", "قیمت", ["price"]),
];

const orderFields = [
  field("orderDirection", "enum", "Order direction", "جهت سفارش", ["order"]),
  field("orderReactionNumber", "integer", "Order reaction number", "شماره ری‌اکشن سفارش", ["order", "reaction"]),
  field("orderMode", "enum", "Order mode", "حالت سفارش", ["order"]),
  field("orderCauses", "list", "Order causes", "علت‌های سفارش", ["order", "cause"]),
  field("orderParentStopCauseTime", "datetime?", "Parent-stop cause time", "زمان علت استاپ والد", ["order", "stop", "time"]),
  field("orderResetLegResetTime", "datetime?", "Reset-leg reset time", "زمان ریست در لگ سفارش", ["order", "reset", "time"]),
  field("orderResetLegBreakTime", "datetime?", "Reset-leg break time", "زمان شکست لگ ریست", ["order", "reset", "time"]),
  field("orderFirstIndex", "integer", "Order first index", "شماره اولین کندل سفارش", ["order", "source"]),
  field("orderFirstTime", "datetime", "Order first time", "زمان شروع سفارش", ["order", "time"]),
  field("orderBreakIndex", "integer", "Order break index", "شماره کندل شکست سفارش", ["order", "break"]),
  field("orderBreakTime", "datetime", "Order break time", "زمان شکست سفارش", ["order", "break", "time"]),
  field("orderConfirmationTime", "datetime", "Order confirmation time", "زمان تأیید سفارش", ["order", "time"]),
  field("orderBoxTop", "decimal", "Order box top", "سقف باکس سفارش", ["order", "box", "price"]),
  field("orderBoxTopSourceIndex", "integer", "Order box-top source index", "شماره کندل منبع سقف سفارش", ["order", "box", "source"]),
  field("orderBoxTopSourceTime", "datetime", "Order box-top source time", "زمان منبع سقف سفارش", ["order", "box", "time"]),
  field("orderBoxBottom", "decimal", "Order box bottom", "کف باکس سفارش", ["order", "box", "price"]),
  field("orderBoxBottomSourceIndex", "integer", "Order box-bottom source index", "شماره کندل منبع کف سفارش", ["order", "box", "source"]),
  field("orderBoxBottomSourceTime", "datetime", "Order box-bottom source time", "زمان منبع کف سفارش", ["order", "box", "time"]),
  field("orderStopLevel", "decimal", "Order stop level", "سطح استاپ سفارش", ["order", "stop", "price"]),
  field("orderStopSourceIndex", "integer", "Order stop source index", "شماره کندل منبع استاپ", ["order", "stop", "source"]),
  field("orderStopSourceTime", "datetime", "Order stop source time", "زمان منبع استاپ", ["order", "stop", "time"]),
];

const decisionFields = [
  field("decisionIndex", "integer", "Decision candle index", "شماره کندل تصمیم", ["decision"]),
  field("decisionTime", "datetime", "Decision time", "زمان تصمیم", ["decision", "time"]),
  field("decisionEventTime", "datetime", "Decision event time", "زمان دقیق رویداد تصمیم", ["decision", "time"]),
];

const FIELD_TYPE_OVERRIDES = Object.freeze({
  "blueLines.previousStrikeCount": "integer?",
  "blueLines.strikeCount": "integer?",
  "sZones.formationType": "enum",
  "sZones.orderDirection": "enum?",
  "sZones.orderReactionNumber": "integer?",
  "sZones.orderMode": "enum?",
  "sZones.orderFirstIndex": "integer?",
  "sZones.orderFirstTime": "datetime?",
  "sZones.orderBreakIndex": "integer?",
  "sZones.orderBreakTime": "datetime?",
  "sZones.orderConfirmationTime": "datetime?",
  "sZones.orderBoxTop": "decimal?",
  "sZones.orderBoxTopSourceIndex": "integer?",
  "sZones.orderBoxTopSourceTime": "datetime?",
  "sZones.orderBoxBottom": "decimal?",
  "sZones.orderBoxBottomSourceIndex": "integer?",
  "sZones.orderBoxBottomSourceTime": "datetime?",
  "sZones.orderStopLevel": "decimal?",
  "sZones.orderStopSourceIndex": "integer?",
  "sZones.orderStopSourceTime": "datetime?",
  "sZones.resetReactionNumber": "integer?",
  "sZones.resetTime": "datetime?",
  "orderAudit.stopHitIndex": "integer?",
  "orderAudit.stopHitTime": "datetime?",
  "orderAudit.stopHitEventTime": "datetime?",
  "stopAlls.stopIndex": "integer?",
});

const bridgeObjects = [
  {
    id: "reaction", collection: "reactions", stage: 1, tags: ["reaction", "box", "break"],
    names: { en: "Reaction", fa: "ری‌اکشن" },
    description: { en: "Confirmed reaction geometry calculated by the reaction engine.", fa: "هندسه کامل ری‌اکشن که موتور محاسباتی تأیید کرده است." },
    fields: [
      field("firstIndex", "integer", "First candle index", "شماره اولین کندل", ["reaction", "source"]),
      field("firstTime", "datetime", "First candle time", "زمان اولین کندل", ["reaction", "time"]),
      field("boxTopSourceIndex", "integer", "Box-top source index", "شماره کندل منبع سقف باکس", ["reaction", "box", "source"]),
      field("boxTopSourceTime", "datetime", "Box-top source time", "زمان منبع سقف باکس", ["reaction", "box", "time"]),
      field("boxTop", "decimal", "Box top", "سقف باکس", ["reaction", "box", "price"]),
      field("boxBottomSourceIndex", "integer", "Box-bottom source index", "شماره کندل منبع کف باکس", ["reaction", "box", "source"]),
      field("boxBottomSourceTime", "datetime", "Box-bottom source time", "زمان منبع کف باکس", ["reaction", "box", "time"]),
      field("boxBottom", "decimal", "Box bottom", "کف باکس", ["reaction", "box", "price"]),
      field("breakIndex", "integer", "Break candle index", "شماره کندل شکست", ["reaction", "break"]),
      field("breakTime", "datetime", "Break time", "زمان شکست", ["reaction", "break", "time"]),
      field("mode", "enum", "Reaction mode", "حالت ری‌اکشن", ["reaction", "mode"]),
    ],
  },
  {
    id: "reset", collection: "resets", stage: 1, tags: ["reset", "reaction", "break"],
    names: { en: "Reaction Reset", fa: "ریست ری‌اکشن" },
    description: { en: "Accepted reaction reset boundary.", fa: "مرز ریستی که موتور ری‌اکشن پذیرفته است." },
    fields: [
      field("index", "integer", "Reset candle index", "شماره کندل ریست", ["reset"]),
      field("time", "datetime", "Display time", "زمان نمایش", ["reset", "time"]),
      field("secondTime", "datetime?", "Exact lower-timeframe time", "زمان دقیق در تایم‌فریم پایین‌تر", ["reset", "time"]),
      field("brokenLevel", "decimal", "Broken level", "سطح شکسته‌شده", ["reset", "break", "price"]),
      field("fromFirstIndex", "integer", "Owner reaction first index", "شماره اولین کندل ری‌اکشن مالک", ["reset", "reaction", "ownership"]),
    ],
  },
  {
    id: "blue_line", collection: "blueLines", stage: 2, tags: ["blue-line", "fibonacci", "reaction", "reset"],
    names: { en: "Blue Line", fa: "خط آبی" },
    description: { en: "Blue-line strikes, Fibonacci level and reset line events.", fa: "ضربه‌های خط آبی، سطح فیبوناچی و رویدادهای خط ریست." },
    fields: [
      field("direction", "enum", "Direction", "جهت", ["direction"]),
      field("kind", "enum", "Line kind", "نوع خط", ["blue-line", "reset"]),
      field("reactionNumber", "integer", "Reaction number", "شماره ری‌اکشن", ["reaction"]),
      field("previousStrikeCount", "integer", "Previous strike count", "تعداد ضربه قبلی", ["blue-line", "strike"]),
      field("strikeCount", "integer", "Strike count", "تعداد ضربه", ["blue-line", "strike"]),
      field("fibonacciLevel", "decimal?", "Fibonacci 0.618 level", "سطح فیبوناچی ۰٫۶۱۸", ["fibonacci", "price"]),
      field("sourceIndex", "integer", "Source candle index", "شماره کندل منبع", ["source"]),
      field("sourceTime", "datetime", "Source time", "زمان منبع", ["source", "time"]),
      field("sourceExtreme", "decimal", "Source extreme", "اکستریم منبع", ["source", "price"]),
      field("brokenLevel", "decimal?", "Broken level", "سطح شکسته‌شده", ["break", "reset", "price"]),
      field("linePrice", "decimal", "Line price", "قیمت خط", ["blue-line", "price"]),
      field("startTime", "datetime", "Line start time", "زمان شروع خط", ["blue-line", "time"]),
      field("endTime", "datetime", "Line end time", "زمان پایان خط", ["blue-line", "time"]),
    ],
  },
  {
    id: "a", collection: "aZones", stage: 3, tags: ["a", "blue-line", "reaction", "stop"],
    names: { en: "A", fa: "رفتار A" },
    description: { en: "A behavior built from two blue-line states and its owning reaction.", fa: "رفتار A که از دو وضعیت خط آبی و ری‌اکشن مالک ساخته می‌شود." },
    fields: [
      field("direction", "enum", "Direction", "جهت", ["direction"]),
      field("blue1Ordinal", "integer", "First blue-line ordinal", "شماره خط آبی اول", ["blue-line"]),
      field("blue2Ordinal", "integer", "Second blue-line ordinal", "شماره خط آبی دوم", ["blue-line"]),
      field("blue1SourceTime", "datetime", "First blue-line source time", "زمان منبع خط آبی اول", ["blue-line", "time"]),
      field("blue2SourceTime", "datetime", "Second blue-line source time", "زمان منبع خط آبی دوم", ["blue-line", "time"]),
      field("blue1StopTime", "datetime", "First blue-line stop time", "زمان استاپ خط آبی اول", ["blue-line", "stop", "time"]),
      field("blue2StopTime", "datetime", "Second blue-line stop time", "زمان استاپ خط آبی دوم", ["blue-line", "stop", "time"]),
      field("blue1StopLevel", "decimal", "First blue-line stop level", "سطح استاپ خط آبی اول", ["blue-line", "stop", "price"]),
      field("blue2StopLevel", "decimal", "Second blue-line stop level", "سطح استاپ خط آبی دوم", ["blue-line", "stop", "price"]),
      field("continuationLevel", "decimal", "Continuation level", "سطح ادامه حرکت", ["continuation", "price"]),
      field("continuationSourceIndex", "integer", "Continuation source index", "شماره کندل منبع ادامه حرکت", ["continuation", "source"]),
      field("continuationSourceTime", "datetime", "Continuation source time", "زمان منبع ادامه حرکت", ["continuation", "time"]),
      field("triggerIndex", "integer", "Trigger candle index", "شماره کندل تریگر", ["trigger"]),
      field("triggerTime", "datetime", "Trigger time", "زمان تریگر", ["trigger", "time"]),
      field("triggerEventTime", "datetime", "Exact trigger event time", "زمان دقیق رویداد تریگر", ["trigger", "time"]),
      field("reactionNumber", "integer", "Reaction number", "شماره ری‌اکشن", ["reaction"]),
      field("reactionFirstTime", "datetime", "Reaction first time", "زمان شروع ری‌اکشن", ["reaction", "time"]),
      field("reactionBreakTime", "datetime", "Reaction break time", "زمان شکست ری‌اکشن", ["reaction", "break", "time"]),
      ...commonEvent,
      field("calculationValid", "boolean", "Calculation is valid", "معتبر بودن محاسبه", ["validity"]),
    ],
  },
  {
    id: "s", collection: "sZones", stage: 4, tags: ["s", "a", "reaction", "order", "reset"],
    names: { en: "S Red / S Blue", fa: "S قرمز / S آبی" },
    description: { en: "S family, formation type, order geometry and reset lineage.", fa: "خانواده S، نوع تشکیل، هندسه سفارش و مسیر ریست آن." },
    fields: [
      field("direction", "enum", "Direction", "جهت", ["direction"]),
      field("color", "enum", "S color", "رنگ S", ["s", "color"]),
      field("formationType", "integer", "Formation type", "نوع تشکیل", ["s", "formation"]),
      field("aOrdinal", "integer", "A ordinal", "شماره A", ["a"]),
      field("aSourceIndex", "integer", "A source index", "شماره کندل منبع A", ["a", "source"]),
      field("aSourceTime", "datetime", "A source time", "زمان منبع A", ["a", "time"]),
      field("aPrice", "decimal", "A price", "قیمت A", ["a", "price"]),
      field("aStopIndex", "integer", "A stop index", "شماره کندل استاپ A", ["a", "stop"]),
      field("aStopTime", "datetime", "A stop time", "زمان استاپ A", ["a", "stop", "time"]),
      field("aStopEventTime", "datetime", "Exact A stop event time", "زمان دقیق رویداد استاپ A", ["a", "stop", "time"]),
      ...orderFields.filter((item) => !item.id.startsWith("orderCauses") && !item.id.startsWith("orderParent") && !item.id.startsWith("orderReset")),
      field("resetReactionNumber", "integer?", "Reset reaction number", "شماره ری‌اکشن ریست", ["reset", "reaction"]),
      field("resetTime", "datetime?", "Reset time", "زمان ریست", ["reset", "time"]),
      ...commonEvent,
      ...decisionFields,
      field("calculationValid", "boolean", "Calculation is valid", "معتبر بودن محاسبه", ["validity"]),
    ],
  },
  {
    id: "e", collection: "eZones", stage: 5, tags: ["e", "s", "order", "stop", "ownership"],
    names: { en: "E Red / E Blue", fa: "E قرمز / E آبی" },
    description: { en: "E sequence, parent ownership and complete inherited order.", fa: "دنباله E، مالکیت والد و تمام اطلاعات سفارش به‌ارث‌رسیده." },
    fields: [
      ...commonEvent,
      field("family", "enum", "E family", "خانواده E", ["e", "family"]),
      field("number", "integer", "E number", "شماره E", ["e", "sequence"]),
      field("parentType", "enum", "Parent type", "نوع والد", ["parent", "ownership"]),
      field("parentSourceIndex", "integer", "Parent source index", "شماره کندل منبع والد", ["parent", "source"]),
      field("parentSourceTime", "datetime", "Parent source time", "زمان منبع والد", ["parent", "time"]),
      field("parentPrice", "decimal", "Parent price", "قیمت والد", ["parent", "price"]),
      field("parentStopIndex", "integer", "Parent stop index", "شماره کندل استاپ والد", ["parent", "stop"]),
      field("parentStopTime", "datetime", "Parent stop time", "زمان استاپ والد", ["parent", "stop", "time"]),
      field("parentStopEventTime", "datetime", "Exact parent stop event time", "زمان دقیق رویداد استاپ والد", ["parent", "stop", "time"]),
      ...orderFields,
      ...decisionFields,
    ],
  },
  {
    id: "stop_all", collection: "stopAlls", stage: 6, tags: ["stop-all", "e", "s", "order", "reset", "ownership"],
    names: { en: "StopAll", fa: "توقف همه" },
    description: { en: "Final sequence reset and the stopped behavior/order lineage.", fa: "ریست نهایی دنباله به‌همراه رفتار متوقف‌شده و مسیر کامل سفارش." },
    fields: [
      ...commonEvent,
      field("number", "integer", "StopAll number", "شماره StopAll", ["stop-all", "sequence"]),
      ...decisionFields,
      field("gateType", "enum", "Gate type", "نوع دروازه", ["gate"]),
      field("gateEventTime", "datetime", "Gate event time", "زمان رویداد دروازه", ["gate", "time"]),
      field("stoppedBehaviorType", "enum", "Stopped behavior type", "نوع رفتار متوقف‌شده", ["stop", "behavior"]),
      field("stoppedBehaviorKey", "string", "Stopped behavior key", "کلید رفتار متوقف‌شده", ["stop", "behavior"]),
      field("stoppedBehaviorCount", "integer", "Stopped behavior count", "تعداد رفتارهای متوقف‌شده", ["stop", "behavior"]),
      field("underlyingEFamily", "enum", "Underlying E family", "خانواده E زیرمجموعه", ["e", "family"]),
      field("underlyingENumber", "integer", "Underlying E number", "شماره E زیرمجموعه", ["e", "sequence"]),
      ...orderFields,
      field("stopIndex", "integer", "Stop candle index", "شماره کندل استاپ", ["stop"]),
      field("stopTime", "datetime?", "Stop time", "زمان استاپ", ["stop", "time"]),
      field("stopEventTime", "datetime?", "Exact stop event time", "زمان دقیق رویداد استاپ", ["stop", "time"]),
    ],
  },
  {
    id: "order_audit", collection: "orderAudit", stage: 5, tags: ["order", "audit", "reaction", "stop", "cause"],
    names: { en: "Order Audit", fa: "ردیابی سفارش" },
    description: { en: "Auditable order geometry, stop result and every formation cause.", fa: "هندسه قابل‌ردیابی سفارش، نتیجه استاپ و تمام علت‌های تشکیل." },
    fields: [
      field("direction", "enum", "Direction", "جهت", ["direction"]),
      field("reactionNumber", "integer", "Reaction number", "شماره ری‌اکشن", ["reaction"]),
      field("reactionMode", "enum", "Reaction mode", "حالت ری‌اکشن", ["reaction", "mode"]),
      field("firstIndex", "integer", "First candle index", "شماره اولین کندل", ["reaction", "source"]),
      field("firstTime", "datetime", "First candle time", "زمان اولین کندل", ["reaction", "time"]),
      field("boxTopSourceIndex", "integer", "Box-top source index", "شماره کندل منبع سقف باکس", ["reaction", "box", "source"]),
      field("boxTopSourceTime", "datetime", "Box-top source time", "زمان منبع سقف باکس", ["reaction", "box", "time"]),
      field("boxTop", "decimal", "Box top", "سقف باکس", ["reaction", "box", "price"]),
      field("boxBottomSourceIndex", "integer", "Box-bottom source index", "شماره کندل منبع کف باکس", ["reaction", "box", "source"]),
      field("boxBottomSourceTime", "datetime", "Box-bottom source time", "زمان منبع کف باکس", ["reaction", "box", "time"]),
      field("boxBottom", "decimal", "Box bottom", "کف باکس", ["reaction", "box", "price"]),
      field("breakIndex", "integer", "Break candle index", "شماره کندل شکست", ["reaction", "break"]),
      field("breakTime", "datetime", "Break time", "زمان شکست", ["reaction", "break", "time"]),
      field("stopLevel", "decimal", "Stop level", "سطح استاپ", ["stop", "price"]),
      field("stopSourceIndex", "integer", "Stop source index", "شماره کندل منبع استاپ", ["stop", "source"]),
      field("stopSourceTime", "datetime", "Stop source time", "زمان منبع استاپ", ["stop", "time"]),
      field("stopHitIndex", "integer?", "Stop-hit index", "شماره کندل برخورد با استاپ", ["stop"]),
      field("stopHitTime", "datetime?", "Stop-hit time", "زمان برخورد با استاپ", ["stop", "time"]),
      field("stopHitEventTime", "datetime?", "Exact stop-hit event time", "زمان دقیق برخورد با استاپ", ["stop", "time"]),
      field("causes", "list", "Formation causes", "علت‌های تشکیل", ["cause", "order"]),
    ],
  },
];

// Every field inherits the identity, collection and family tags of its Bridge
// object so documentation search can never hide a calculated field.
export const BRIDGE_OBJECT_CATALOG = Object.freeze(bridgeObjects.map((object) => Object.freeze({
  ...object,
  tags: Object.freeze([...new Set([object.id, object.collection, ...object.tags])]),
  fields: Object.freeze(object.fields.filter((item, index, fields) => fields.findIndex((candidate) => candidate.id === item.id) === index).map((item) => Object.freeze({
    ...item,
    type: FIELD_TYPE_OVERRIDES[`${object.collection}.${item.id}`] || item.type,
    tags: Object.freeze([...new Set([object.id, object.collection, ...object.tags, ...item.tags])]),
  }))),
})));

export function bridgeObject(id) {
  return BRIDGE_OBJECT_CATALOG.find((item) => item.id === id) || null;
}

export function catalogFieldPaths() {
  return BRIDGE_OBJECT_CATALOG.flatMap((object) => object.fields.map((item) => ({
    ...item,
    objectId: object.id,
    collection: object.collection,
    path: `${object.collection}.${item.id}`,
  })));
}
